### ISSUE TITLE
Number of parameters mismatch

### ISSUE THREAD

**Issue by ghost** [BUseclab/paybreak#1]
The functions 'GenSessionKeyWithRandom' and 'GenSessionKeyWithPassword' expect 5 and 7 parameters, respectively. However, when they are called from KEncrypt.cpp file, they pass only 4 and 6 parameters which result in compilation errors.

**Comment by eugenekolo** [comment]
Fixed in: https://github.com/BUseclab/paybreak/commit/89f04549a57b1d78dca96e8c7cf9231991693612
