### ISSUE TITLE
CryptEncrypt attached with CryptDestroyKey

### ISSUE THREAD

**Issue by ghost** [BUseclab/paybreak#2]
File: antiransom.cpp Line 601:
DetourAttach(&(PVOID&)Real_CryptEncrypt, Fake_CryptDestroyKey);

**Comment by eugenekolo** [comment]
This shouldn't effect you. Below it, the CryptEncrypt is attached to the correct thing.

This does make hooking CryptDestroyKey not work, but hooking that's not too useful.

**Comment by eugenekolo** [comment]
Fixed in: https://github.com/BUseclab/paybreak/commit/89f04549a57b1d78dca96e8c7cf9231991693612
