### ISSUE TITLE
problem with variables

### ISSUE THREAD

**Issue by rout3rx** [BUseclab/paybreak#3]
I have a problem with retrieving arguments with functions.
what's the variable with these functions?
please find the attachment.
thanks
![photo_2017-09-09_09-13-14](https://user-images.githubusercontent.com/30006945/30237086-44006c1e-953f-11e7-9368-fc4ffaf6b9a9.jpg)
![photo_2017-09-09_09-13-10](https://user-images.githubusercontent.com/30006945/30237087-4413d9de-953f-11e7-89e0-4b4143971fb6.jpg)

**Comment by eugenekolo** [comment]
Fixed in: https://github.com/BUseclab/paybreak/commit/89f04549a57b1d78dca96e8c7cf9231991693612
